version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jijibot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4t4lz56sfer"
s3_prefix = "jijibot"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "LineChannelAccessToken=\"pa6RVTYGLOMWGn6rY4wFucBDLcFmh5pQgWQw5Da6E6lxraZzPKgc9yqGdbSYpBTe6pu13u5nVv9e5K4Q5XZZfCRjnboDF6lbh6UaHjnJm5OBYkcq6RT8zLmc725v6z2hC2zzG+YJnqlDDhwFnJz8jgdB04t89/1O/w1cDnyilFU=\" LineChannelSecret=\"49c7d20eec8391c9854b6876cc863779\""
image_repositories = []
